### PR TITLE
Remove contents that have no text

### PR DESCRIPTION
**Pull request by TomoyukiHata**

### CODE REVIEW

**Review by nishidai-andaze — CHANGES_REQUESTED** [review]
@TomoyukiHata Please delete the code you don't want rather than commenting it out; you can revert it in Git.

**Comment by TomoyukiHata** [comment]
@nishidai-andaze 
deleted code

**Comment by nishidai-andaze** [comment]
@TomoyukiHata Resolve conflicts.

**Comment by TomoyukiHata** [comment]
@nishidai-andaze 
done

**Review by nishidai-andaze — APPROVED** [review]

**Pull request merged**
